language: node_js
node_js:
  - '10'
script:
  - yarn run tsc
  - yarn run lint
  - yarn run prettier:check
  - yarn run test
  - yarn run build
  - yarn run deploy:github
cache:
  yarn: true
  directories:
    - public
deploy:
  local_dir: public
  provider: pages
   # Set in the settings page of your repository, as a secure variable
  github_token: $GITHUB_TOKEN 
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
