# https://github.com/MicrosoftDocs/pipelines-javascript/blob/master/azure-pipelines.yml
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  
- script: |
    npm install -g yarn
    yarn
    yarn run ci
